[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
automerge = "0.5.12"
automerge_repo = { version = "0.1.0", features = ["tokio"] }
tokio = { version = "1.41.1", features = ["full"] }
