[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
automerge = "0.5.12"
automerge_repo = { git="https://github.com/automerge/automerge-repo-rs.git", features = ["tokio"] }
tokio = { version = "1.41.1", features = ["full"] }
tracing-subscriber = "0.3.18"
