name: Godot Patchwork Plugin Build
description: Build Godot plugin for Patchwork.

inputs:
  arch:
    required: true
    default: ''
    description: Rust target platform.
  
runs:
  using: composite
  steps:
    - run: git --version
      shell: sh
    - uses: extractions/setup-just@v3
    - name: Update Rust
      shell: sh
      run: |
        rustup update
    - name: Show targets
      shell: sh
      run: |
        rustc --print=target-list
    - name: Add additional arm64 target for macOS
      shell: sh
      if: ${{ inputs.arch == 'x86_64-apple-darwin'}}
      run: |
        rustup target add aarch64-apple-darwin
    - name: Rust add current target
      shell: sh
      run: |
        rustup target add ${{ inputs.arch }}
    - name: Build for Windows and Linux
      shell: sh
      if: ${{ inputs.arch == 'x86_64-apple-darwin'}}
      run: |
        just build-patchwork release ${{ inputs.arch }}
    - name: Build for Mac
      shell: sh
      if: ${{ inputs.arch == 'x86_64-apple-darwin'}}
      run: |
        just build-patchwork release "all-apple-darwin"
    - name: Copy to release
      shell: sh
      run: |
        mkdir -p target/release
        rm -rf target/release
        cp -rf target/${{ inputs.arch }}/release target/release
