name: 🪟 Build Patchwork for Windows
on:
  workflow_call:

jobs:
  build-windows:
    runs-on: "windows-latest"
    name: 📐 Build ${{ matrix.arch }}
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        # ARM32 Is not officially supported yet, you need to self build rust target.
        arch: ["x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc"] #, , "i686-pc-windows-msvc", "aarch64-pc-windows-msvc", "thumbv7a-pc-windows-msvc"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Restore Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: patchwork_rust_plugin_windows-${{ matrix.arch }}
      - name: Build
        uses: ./.github/actions/build-plugin
        with:
          arch: ${{ matrix.arch }}
      - name: Windows Sign
        uses: ./.github/actions/windows-sign
        with:
          BINARY_PATHS: |
            ./build/patchwork/bin/patchwork_rust_core.windows.${{ matrix.arch }}.dll
          KMS_CREDENTIALS_JSON: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          KMS_PUBLIC_CERT: ${{ secrets.CODESIGN_PUBLIC_CERT }}
          KMS_PROJECT: ${{ secrets.KMS_PROJECT }}
          KMS_LOCATION: ${{ secrets.KMS_LOCATION }}
          KMS_KEYRING: ${{ secrets.KMS_KEYRING }}
          KMS_KEY: ${{ secrets.KMS_KEY }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: patchwork-build-windows-${{ matrix.arch }}
          path: ./build/patchwork/*
          if-no-files-found: error
